### ISSUE TITLE
Using builtin physics generates no ActorNodes

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/panda3d-gltf#100]
Unlike bullet, where physics uses one class combining actual physics (eg, the force of gravity) and collisions between shapes, the builtin physics system uses two sets of nodes; `ActorNode`s for actual physics, and `CollisionNode`s for collisions between shapes.

Currently, panda3d-gltf only generates `CollisionNode`s and not `ActorNode`s, resulting in dropping things like mass.

**Comment by Clockwork-Muse** [comment]
Related to this, there appear to be a lot of "empty" (for lack of a better word) `PandaNode`s in a hierarchy:

```
ModelRoot Scene T:(pos 0 -1 0)
  Character Armature
    PandaNode A-A
      GeomNode A-B (1 geoms: S:(CullFaceAttrib MaterialAttrib TextureAttrib))
    PandaNode C-A T:m(pos 0 0.0814439 0.299334 hpr 0 5.90508 0)
      BulletGhostNode C-B (1 shapes) active
        GeomNode C-C (1 geoms: S:(MaterialAttrib TextureAttrib))
```
... should things be changed around to remove these extra nodes?

**Comment by rdb** [comment]
I could be mistaken, but panda3d-gltf does not support the built-in physics system.  "builtin" in this case refers to the built-in collision system.

panda3d-gltf makes no attempt to optimize the hierarchy, rather this node structure is to ensure correctness.  You can use `flattenMedium()` in an additional pass to get rid of intermediate nodes.
