### ISSUE TITLE
load .gtlf model file error

### ISSUE THREAD

**Issue by dooliu** [Moguri/panda3d-gltf#108]
I use panda3d-gltf load .gltf 3D model file，but the result is strange，as shown below:
the .gltf file use Meya，3DMax and other tools open, the reslut is normal;
when i use code load model file, the model is become a whole white thing.

the whole code as below:
        # Load the environment model.
        gltf.patch_loader(self.loader)
        self.scene = self.loader.loadModel("models/environment")
        # Reparent the model to render.
        self.scene.reparentTo(self.render)
        # Apply scale and position transforms on the model.
        self.scene.setScale(0.25, 0.25, 0.25)
        self.scene.setPos(-8, 42, 0)

        # Add the spinCameraTask procedure to the task manager.
        # self.taskMgr.add(self.spinCameraTask, "SpinCameraTask")

        # Load and transform the panda actor.
        gltf.patch_loader(self.loader)
        self.pandaActor = Actor("qt.gltf")
        self.pandaActor.setScale(10, 10, 10)
        self.pandaActor.setHpr(Point3(180, 0, 0))
        self.pandaActor.reparentTo(self.render)

Is there something wrong with my code?

**Comment by Kupoman** [comment]
An image of expected, such as from Max or Maya, and actual behavior could be useful here.

I am just taking a guess here, but it sound like textures may not be loading properly. Are any textures embedded in the file, or stored separately?

**Comment by Moguri** [comment]
We'll need a sample file that demonstrates the issue. I suspect that your scene is missing lights.

**Comment by Moguri** [comment]
Closing due to lack of information/activity. Another common issue is fully metallic objects look funky due to missing IBL in simplepbr.
