### ISSUE TITLE
__file__ references cause problems when freezing for web

### ISSUE THREAD

**Issue by Kupoman** [Moguri/panda3d-gltf#109]
There are two cases where the `__file__` reference is used for loading PRC data. These references seem to cause problems when attempting to freeze a Panda3D project for the web (https://rdb.name/panda3d-webgl.md.html).

The first is in `converter.py`:
```python
load_prc_file_data(
    __file__,
    'interpolate-frames #t\n'
)
```

The second is in `viewer.py`:
```python
p3d.load_prc_file_data(
    __file__,
    'window-size 1024 768\n'
    'texture-minfilter mipmap\n'
    'texture-anisotropic-degree 16\n'
)
```

It would be nice to be able to avoid these references when using `panda-gltf` as a library. The `viewer.py` case can likely be resolved by moving the call into the "if main" block at the bottom of the file. However, I am not sure how to resolve the case in converter.py. I deleted it locally, but I doubt that is ideal.

**Comment by rdb** [comment]
This is a general problem with freezing causing `__file__` to be unavailable.  A workaround would be to assign `builtins.__file__` to something, I believe the normal deployment process does this but not the freezify.py script that I made available for building WebGL.

The first argument to `load_prc_file_data` is generally without consequence and just used to name the config page.  It could be changed to anything else.

**Comment by Kupoman** [comment]
Thanks!
