### ISSUE TITLE
Models with textures are not stored correctly in cache

### ISSUE THREAD

**Issue by el-dee** [Moguri/panda3d-gltf#118]
This is a regression introduced by 27ef4ae21088b6d88b9761987a7321200908331a

If I load a .gltf model with textures twice, the second time there are errors in the log about texture not found and the models is rendered without any textures.

This is the output witht the BoomBox model from gLTF:
<pre>
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:gobj(error): Texture::read() - couldn't read: BoomBox_baseColor.png
:gobj(error): Unable to find texture "BoomBox_baseColor.png" on model-path /home/ld/Projects/gltf/gltf:/usr/share/panda3d:/usr/share/panda3d/models
:gobj(error): Texture::read() - couldn't read: BoomBox_occlusionRoughnessMetallic.png
:gobj(error): Unable to find texture "BoomBox_occlusionRoughnessMetallic.png" on model-path /home/ld/Projects/gltf/gltf:/usr/share/panda3d:/usr/share/panda3d/models
:gobj(error): Texture::read() - couldn't read: BoomBox_normal.png
:gobj(error): Unable to find texture "BoomBox_normal.png" on model-path /home/ld/Projects/gltf/gltf:/usr/share/panda3d:/usr/share/panda3d/models
:gobj(error): Texture::read() - couldn't read: BoomBox_emissive.png
:gobj(error): Unable to find texture "BoomBox_emissive.png" on model-path /home/ld/Projects/gltf/gltf:/usr/share/panda3d:/usr/share/panda3d/models
</pre>

The viewer does not show the issue as the cache is disabled and the directory containing the .gltf file is prepended to the model path list (which is something an actual app should not do as models could have textures using the same filename but with different content)

The fix seems trivial: the following line 

https://github.com/Moguri/panda3d-gltf/blob/cd8387f2f965ff9fca8b0eaeb023d1e7d2597fac/gltf/converter.py#L521

should be replaced by:

```python
texture.filename = uri
```

but I fear any side effects or consequences on e.g. `gltf2bam`

**Comment by Moguri** [comment]
I went ahead and applied the fix. Tests are passing, and I ran into no issues with one of my projects that uses blend2bam/panda3d-gltf. Unfortunately, I do not remember why I originally needed to set `fullpath` there.

We'll see if someone  complains about the change and then I can write a test case to catch it.
