### ISSUE TITLE
Model crashed when exporting to glb from blender.

### ISSUE THREAD

**Issue by SoNewBee** [Moguri/panda3d-gltf#124]
https://sketchfab.com/3d-models/ruby-rose-2270ee59d38e409491a76451f6c6ef80

I tested this model.
When I export it to glb format from blender and check it in gltf-viewer,the model will crash (very scary).

**Comment by Moguri** [comment]
Could you either upload the glb file or tell me how I can pull the model from that site? I may be missing something, but I cannot seem to find a download link.

**Comment by SoNewBee** [comment]
https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/tree/master/examples/ruby_rose
You can check this and download it from there.

**Comment by Moguri** [comment]
I grabbed that file and exported as glb from Blender (leaving options as defaults). The model loads in `gltf-viewer`, but the animation and/or skinning is a bit of a mess. No crash though.

**Comment by SoNewBee** [comment]
> The model loads in `gltf-viewer`, but the animation and/or skinning is a bit of a mess.

Yes,this is what display on my comuter.
![image](https://github.com/Moguri/panda3d-gltf/assets/51787223/26bab02e-a062-4bd9-a254-b7c1553f01e9)

**Comment by developer-1v** [comment]
I had something similar happen. Upgrading from 0.14 to 0.15 caused the issue.  1.0.0 issue remains. The model will load in just fine. But once the animation starts, it goes into "Japanese monster mode."

Extra info: I'm using a y=up coordinate system. but trying to change the coordinates doesn't fix the problem. Some of my models with animations are completely fine, but this one is not. 

![panda3d-gltf v 0 14 vs v 0 15](https://github.com/Moguri/panda3d-gltf/assets/116611660/79ac7a28-28c1-4c70-bbe8-2543b851a756)

**Comment by developer-1v** [comment]
@SoNewBee  You can downgrade to 0.14 for now as a temporary band-aid. But be sure to delete the bam model in your panda3d cache. Also, when I upgrade panda3d, it auto-upgrades the panda3d-gltf to the newest 1.0.0, so remember to downgrade again until this gets a patch. 

`pip install --no-cache --force-reinstall panda3d-gltf==0.14`
Windows panda3d cache: `C:\Users\YourNameHere\AppData\Local\Panda3D-1.10`

**Comment by SoNewBee** [comment]
> @SoNewBee You can downgrade to 0.14 for now as a temporary band-aid. But be sure to delete the bam model in your panda3d cache. Also, when I upgrade panda3d, it auto-upgrades the panda3d-gltf to the newest 1.0.0, so remember to downgrade again until this gets a patch.
> 
> `pip install --no-cache --force-reinstall panda3d-gltf==0.14` Windows panda3d cache: `C:\Users\YourNameHere\AppData\Local\Panda3D-1.10`

Thanks,but I don't think that is a good solution.

**Comment by developer-1v** [comment]
panda3d-gltf version 0.15 & 1.0 distort your rig. Downgrading just that module without downgrading panda3d will get rid of that distortion problem. I don't think it can be avoided as all gltf files get converted to .bam files using this library. But if you find another solution, then please let us know. I'd like a more permanent solution as well.
