### ISSUE TITLE
Disabling hidden behavior of shimming loader.loadModel in favor of explicit call.

### ISSUE THREAD

**Issue by csevier** [Moguri/panda3d-gltf#126]
Its a great tool but I find it confusing  that if I pip install panda3d-gltf, unannounced to the user it changes the behavior of their model loads silently. This is against python ethos for explicitness, but practically it can be confusing and jarring. Perhaps this isnt the right place for this, maybe a change to loader behavior to specify the importer youd like to use explicitly in panda itself. Perhaps even adding a method dynamically to loader. Unsure, its just surprising behavior to users.

**Comment by Moguri** [comment]
The Python file loader (the mechanism that his package uses to register a new loader with Panda), is an advertised feature and one of the primary reasons users download the package. So, I would hardly call it "hidden", "unannounced", or "silent".

To disable automatically registering file loaders from Python packages, I believe you can set the `loader-support-entry-points` to `f` or `0`.

**Comment by csevier** [comment]
I suppose that's up to how you interpret the word "seamless". I certainly did not interpret it that way. Sorry for the confusion! Thanks for bringing my attention to the override capability.

**Comment by csevier** [comment]
Can override the behavior and is explicitly desired behavior by authors and others.
