### ISSUE TITLE
Add Python 3.11 and 3.12 to CI pipeline

### ISSUE THREAD

**Issue by ekiefl** [Moguri/panda3d-gltf#135]
Hello, I'm taking a look at all of my package's direct dependencies because it has been requested that I support Python 3.12. 

Anecdotally, it seems that in my application panda3d-gltf works with 3.12 🥳. Would you consider bumping the upper bound of your CI build to 3.12? Currently it's 3.8, 3.9, and 3.10.

**Comment by Moguri** [comment]
Added in 350212621a1d0beb11a2caae1b4124693e68bfa4
