### ISSUE TITLE
Loading is excruciatingly slow when loading .bin from .gltf files

### ISSUE THREAD

**Issue by el-dee** [Moguri/panda3d-gltf#31]
Loading of external .bin files from .gltf files is extremely slow, the root cause is that 
https://github.com/Moguri/panda3d-gltf/blob/fd8cf7427ed5c9b309026c3e3af169d33e8dbd6e/gltf/converter.py#L377

Does not specify the size of the chunk to read from the stream, and the default value is 512 bytes, so for a 11MB file, it means more that 22000 chunk read followed by buffer concatenation, which takes several minutes. Adding size=1024*1024 makes the file load in a jiffy.

**Comment by el-dee** [comment]
Correction, the problem is not in gltf/converter.py but rather in Panda's file library : 

https://github.com/panda3d/panda3d/blob/984d70e8e0e84dec1848965fd336648672b7731d/direct/src/stdpy/file.py#L255

If I specify the size at buff_file.read(), only size bytes are read. If I don't specify the size, chunks of 512 bytes are read. So either the actual file size should be specified or in StreamIOWrapper the chunk size should be increased (a lot)

**Comment by rdb** [comment]
I'll fix this in Panda3D 1.10.5.

**Comment by rdb** [comment]
Actually, byteLength is a required property for buffers.  We should just pass in the byteLength to the read call for best performance.

**Comment by el-dee** [comment]
Tested with the fix in Panda, the files load almost instantly now :)

**Comment by rdb** [comment]
Could you reopen this?  I still think the right fix is for panda3d-gltf to pass in the buffer's byteLength to the read call, which will give panda3d-gltf acceptable performance in Panda3D 1.10.4.1, and better performance in any version.
