### ISSUE TITLE
Nodes have wrong transformation

### ISSUE THREAD

**Issue by el-dee** [Moguri/panda3d-gltf#34]
On some composite models, some nodes have wrong transformation applied to them, resulting in a broken model.

For example, here is a model of the Hubble space telescope : https://exoplanets.nasa.gov/resources/2214/hubble-space-telescope-3d-model/

Which is rendered fine with BabylonJS, Blender, ...

<img width="660" alt="Hubble" src="https://user-images.githubusercontent.com/44778133/66647216-99852e80-ec28-11e9-82bb-b6b88468cb18.png">

But with panda3d-gltf, several parts are not positioned and oriented properly.

<img width="796" alt="Hubble-p3d" src="https://user-images.githubusercontent.com/44778133/66647138-5d51ce00-ec28-11e9-9704-e6b6bc6e4f65.png">

Here is a dump of the loaded scene : 

<pre>
ModelRoot Scene
  PandaNode Light T:m(pos 4.07625 5.90386 -1.00545 hpr -104.532 37.1947 -3.97275)
  PandaNode Camera T:m(pos 7.35889 4.95831 6.92579 hpr -46.692 63.5593 0)
    Camera Camera ( PerspectiveLens )
      PerspectiveLens fov = 22.8952 22.8952
  PandaNode alpha_tex01 T:m(pos 0.0952893 1.45378 -5.57658 hpr -90 -6.48857e-06 180 scale 0.345791)
    GeomNode Cylinder.008 (1 geoms: S:(MaterialAttrib TextureAttrib TransparencyAttrib))
  PandaNode AO_1 T:m(hpr 0 0 -180 scale 2.25687 2.25687 2.68318)
    GeomNode Cylinder.003 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode AO_light T:m(hpr 0 0 -180 scale 2.25687 2.25687 2.68318)
    GeomNode Cylinder.007 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode foil_gold T:m(hpr 0 0 -180 scale 1.05556)
    GeomNode Cube.002 (1 geoms)
  PandaNode foil_silver T:m(hpr 0 0 -180 scale 1.05556)
    GeomNode Cube.000 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode shiny_panel T:m(hpr -90 -4.32571e-06 180 scale 0.345791)
    GeomNode Cylinder.009 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode shiny_panel_cylinder T:m(pos -1.94723e-05 0.72426 3.86028 hpr 0 0 -180 scale 2.25687 2.25687 2.68318)
    GeomNode Cylinder.000 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode tex_01 T:m(hpr -90 -4.32571e-06 180 scale 0.345791)
    GeomNode Cylinder.004 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode tex_02 T:m(hpr 0 0 -180 scale 1.05556)
    GeomNode Cube.001 (1 geoms: S:(MaterialAttrib TextureAttrib))
  PandaNode tex_03 T:m(hpr 0 0 -180 scale 2.25687 2.25687 2.68318)
    GeomNode Cylinder.010 (1 geoms: S:(MaterialAttrib TextureAttrib))
</pre>

What is strange is that the transformation are identical to the values seen in Blender, so maybe the parenting is wrong ?

**Comment by el-dee** [comment]
Problem is in the coordinate system conversion, if I add in the glTF file to skip cs conversion :

    "extensionsUsed": ["BP_zup"]

the model is displayed properly. 

in line,

https://github.com/Moguri/panda3d-gltf/blob/741ae9c44a635d3477d57a5ae715fda755a53a23/gltf/converter.py#L333

I removed self.compose_cs and it solve the problem. I believe the cs transformation is actually applied twice, one in the transform matrix, one on the node path itself :

https://github.com/Moguri/panda3d-gltf/blob/741ae9c44a635d3477d57a5ae715fda755a53a23/gltf/converter.py#L341

**Comment by Moguri** [comment]
`self.compose_cs` is set to `CS_yup_right`, which matches the coordinate space of the incoming glTF data, so I think that `compose_matrix()` call is correct and not causing an extra CS transform. However, something is obviously broken.

**Comment by ragerin** [comment]
I'm having the same issue with simple models exported from Blender's GLTF-exporter.

```
panda3d==1.10.4.1
panda3d-gltf==0.3
```

**Comment by el-dee** [comment]
I looked at how the change of coordinate system is done in Panda, but my knowledge of vector and matrices algebra is not good enough to find something wrong... The only weird thing I saw is that the translation part of a transform matrix is not affected by the change of coordinate system.

As Panda 1.10.5 release is getting close, it would be nice to be sure the bug is not in Panda or have a fix included in the release.

**Comment by rdb** [comment]
The problem is not that we are passing in the wrong coordinate system to `compose_matrix`, but are failing to pass in the correct one to `quat.get_hpr()` when converting the quaternion that we are about to pass in to `compose_matrix`.  I'll prepare a PR.
