### ISSUE TITLE
Model's rotation axis does not match Blender.

### ISSUE THREAD

**Issue by K9Kraken** [Moguri/panda3d-gltf#43]
Using Blender 2.8:

"+Y Up" option checked -> Model in Panda3D is upside down, -Z is up.

"+Y Up" option checked and model converted to bam with "--skip-axis-conversion" -> model in Panda3D is sideways, +Y is up.

"+Y Up" option unchecked -> model in Panda3D is sideways, +Y is up.

"+Y Up" option unchecked and model converted to bam with "--skip-axis-conversion" -> model in Panda3D axis is correct, +Z is up.

**Comment by rdb** [comment]
Which precise version of panda3d-gltf do you have?

**Comment by K9Kraken** [comment]
0.3

I first installed from "pip install panda3d-gltf" about a month ago.
Last week I installed doing:
pip install git+https://github.com/Moguri/panda3d-gltf.git

Same results with both.

**Comment by rdb** [comment]
@Moguri just merged #42 today, can you update to latest Git and see if that fixes it?

**Comment by K9Kraken** [comment]
Pip would not update, but after uninstalling and reinstalling the importer is working correctly.

Now when I export from Blender leaving the defualt "+Y Up" option checked it will load in to Panda3D on the correct axis with +Z as up.

Thanks!
