### ISSUE TITLE
sudo pip gave the following issue

### ISSUE THREAD

**Issue by shenko** [Moguri/panda3d-gltf#55]
Could not find a version that satisfies the requirement panda3d-simplepbr>=0.2.2 (from panda3d-gltf) (from versions: )
No matching distribution found for panda3d-simplepbr>=0.2.2 (from panda3d-gltf)

**Comment by shenko** [comment]
$ pip show panda3d
Name: panda3d
Version: 1.10.0
Summary: Panda3D is a framework for 3D rendering and game development for Python and C++ programs.
Home-page: https://www.panda3d.org/
Author: Panda3D Team
Author-email: etc-panda3d@lists.andrew.cmu.edu
License: Modified BSD License
Location: /usr/local/lib/python2.7/dist-packages
Requires:

**Comment by rdb** [comment]
Looks like you're using an outdated version of Python, 2.7, which is no longer supported.

You should also update your version of Panda3D.  1.10.0 was an unstable version.

**Comment by shenko** [comment]
much obliged good sir

**Comment by Moguri** [comment]
Looks like `panda3d-gltf` had source distributions available on PyPI while `panda3d-simplepbr` only had wheels. Both projects only ship Python 3 wheels, but pip went ahead and tried to use the source distribution of `panda3d-gltf`. I have set a `python_requires` in the `setup.py` to tell pip that this project doesn't support Python 2. Unfortunately, pip will still try to install the older versions that did not set `python_requires`.
