### ISSUE TITLE
TransformBlendTable sometimes assigned when there is no transform_blend column

### ISSUE THREAD

**Issue by rdb** [Moguri/panda3d-gltf#59]
This causes this assertion when trying to flatten the model in Panda:
```
Assertion failed: orig_index >= 0 && orig_index < (int)blend_map.size() at line 1387 of panda/src/pgraph/geomTransformer.cxx
```

This model reproduces the issue:
http://rdb.name/flower.blend

I think the fix is: in combine_mesh_skin, if `tdata.has_column()` returns False, just continue without assigning an empty TransformBlendTable.  However, I don't have the time to test right now.

**Comment by Moguri** [comment]
I played around with the supplied blend file and with a few others (animated and not). The proposed fix allows flower.blend to be flattened, and none of the tested files appeared broken. Thanks!
