### ISSUE TITLE
glTF 2.0 meshes without indices result in empty meshes

### ISSUE THREAD

**Issue by ptc-eparodi** [Moguri/panda3d-gltf#67]
The [glTF 2.0 specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/#primitiveindices) states the indices property is optional for primitives and when not present the same semantics as WebGL drawArrays() should be used to construct the mesh. 

The [TriangleWithoutIndices.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/TriangleWithoutIndices/glTF-Embedded/TriangleWithoutIndices.gltf) model demonstrates this issue. Load the file into the viewer and observe that the model bounding box is empty.

I traced this back to the [converter code](https://github.com/Moguri/panda3d-gltf/blob/master/gltf/converter.py#L837). It looks like only the case of an indexed geometry has been considered. I am wondering if this is just an oversight or it's not a straight forward fix.

**Comment by Moguri** [comment]
This was likely an oversight.

**Comment by ptc-eparodi** [comment]
@Moguri thanks, I think I have got the fix for this issue. How could I grant permission to push a branch with the fix? Thanks.

**Comment by Moguri** [comment]
That's good to hear! Please create a pull request for the change.

**Comment by ptc-eparodi** [comment]
Sorry for the delay. Just created [PR](https://github.com/Moguri/panda3d-gltf/pull/76).

**Comment by Moguri** [comment]
Fixed by PR #76
