### ISSUE TITLE
Broken animation, wrong axis conversion related to NLA and scale

### ISSUE THREAD

**Issue by kergalym** [Moguri/panda3d-gltf#71]
Hi
I exported makehuman character into blender scene, did simple animation (without changing scale or pos) and exported to gltf embedded or glb. Result is same.
 
[untitled.zip](https://github.com/Moguri/panda3d-gltf/files/4707680/untitled.zip)

I didn't include converted bam file since it's big

Exported model has broken anim since its animation wasn't added to NLA editor. Exporting bad models could be prevented by making anim added to NLA track (pushed down) before exporting (optional key) or show some warning about it. Also make scale of armature 1.0 or just show warning to let user manually fix it.

**Comment by kergalym** [comment]
It more affects blend2bam, since it does exporting/converting a model from blend to gltf and then to bam, so I don't know where this issue should be. 
It's interesting that Godot fixes it automatically and don't require anim to be added to NLA track, also YABEE exports it bypassing NLA things (usually I forget to add my anim into that)

**Comment by Moguri** [comment]
All of the stuff with the NLA editor is an exporter issue, and nothing can be done to solve it on the import side. When you say "Godot fixes it automatically" are you using a different exporter for Godot? Most of the exporters for Blender handle this correctly, but the Khronos glTF exporter does not. In any case, blend2bam has a work-around (added yesterday) for the NLA issues in its `master` branch (I have not cut a release yet).

I exported the blend file to glb using the Khronos glTF exporter and it appears to be working for me. Did you upload a blend that has your work-arounds already applied?

**Comment by kergalym** [comment]
> When you say "Godot fixes it automatically" are you using a different exporter for Godot? 

I used glTF exporter (directly exported it from blender)

> Did you upload a blend that has your work-arounds already applied?

No. It was broken unless I changed something in scene before upload...

**Comment by kergalym** [comment]
@Moguri, well, at least animations are fine now, thanks for your fix :) I should make my model scale corrected (vise versa to 1.0 in blender and 0.01 in panda). Closing it.
