### ISSUE TITLE
Lights are positioned/rotated incorrectly

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/panda3d-gltf#81]
Lights have the wrong position/rotation in the viewer.

How it looks in blender:
![image](https://user-images.githubusercontent.com/5569508/100796492-97a29f80-33d5-11eb-8a01-f7a00d5923fb.png)

From [http://gltf.ux3d.io/](http://gltf.ux3d.io/) (viewer linked from Khronos repository):

![image](https://user-images.githubusercontent.com/5569508/100796339-54483100-33d5-11eb-82ba-71c345d33f64.png)

How it looks in the viewer:
![image](https://user-images.githubusercontent.com/5569508/100796584-bdc83f80-33d5-11eb-8cb7-9687f1ea05e3.png)

The file was exported with the default +Y up option checked, but unchecking it doesn't help (I'm not sure where the light is pointing)

[lab.zip](https://github.com/Moguri/panda3d-gltf/files/5625466/lab.zip)

**Comment by rdb** [comment]
For some reason, gltf-viewer reparents all lights to render.  This means the light transformation changes if the light was parented to another node in the gltf file.

**Comment by rdb** [comment]
I also needed to comment out the set_p / set_r calls in converter.py to get the direction of the lights to show up, and I had to comment out the bit that always adds a point light in viewer.py.

**Comment by rdb** [comment]
I pushed some fixes.  The orientation issue was partly due to the viewer reparenting the lights without considering transformations on the parent node, and partly due to the rotation of the lights being set assuming that it is being converted in Z-up mode (as blend2bam does).

**Comment by Clockwork-Muse** [comment]
Thanks!
