### ISSUE TITLE
Support extension KHR_texture_transform

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/panda3d-gltf#86]
Texture information in a gltf file might include mapping information - this might be common with repeated maps, and might include information used to build cards for sprite atlases.

Sample partial gltf:
```gltf
"materials" : [
    {
        "name" : "applesauce",
        "normalTexture" : {
            "extensions" : {
                "KHR_texture_transform" : {
                    "offset" : [
                        -9.99999999999999,
                        1.0000004371139
                    ],
                    "rotation" : 1.5707963705062866,
                    "scale" : [
                        10,
                        10
                    ]
                }
            },
            "index" : 0,
            "scale" : 0.15000000596046448,
            "texCoord" : 0
        },
        "pbrMetallicRoughness" : {
            "baseColorTexture" : {
                "index" : 1,
                "texCoord" : 0
            },
            "metallicFactor" : 0,
            "roughnessFactor" : 0.5
        }
    }
],
```

... I'm not sure where the `offset` value is coming from, here, since my setup in blender looks like this:
![image](https://user-images.githubusercontent.com/5569508/102274350-98105f80-3ed8-11eb-99c2-e4618658177b.png)

**Comment by rdb** [comment]
This is now supported.

The reason for the funny offset in the glTF file is that glTF uses a different transformation origin for the texture coordinates than Blender (and Panda for that matter).

**Comment by Clockwork-Muse** [comment]
Thanks!
