### ISSUE TITLE
Vertex skinning is not performed on all vertices

### ISSUE THREAD

**Issue by el-dee** [Moguri/panda3d-gltf#99]
The glTF sample 'Simple Skin' (https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SimpleSkin) is not animated correctly. Some vertices are not modified at all, contrary to what is expected. 

Here is a snapshot from gltf-viewer :

<img width="912" alt="Simple Skin" src="https://user-images.githubusercontent.com/44778133/107130384-2566a380-68cd-11eb-9e22-1111216f8d9f.png">

Instead we should have something like this :

![](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/SimpleSkin/screenshot/screenshot.gif)

**Comment by rdb** [comment]
I'm looking into it, I suspect an issue reading out the weights, since some of them looking pretty funky, like referencing the same joint twice.

**Comment by rdb** [comment]
It looks like panda3d-gltf currently doesn't support a byteStride that isn't equal to the size of the component.  In the gltf file, the (uint32) index column is only 2 wide (meaning 8 bytes) but it is padded to 16 bytes.

It also looks like the transform indices are being imported as C_other instead of C_index, this is an oversight, but likely harmless.

**Comment by rdb** [comment]
Padded columns are now handled correctly, and the model animates properly now, though it would be great if you could test this on a few models to make sure I haven't broken anything.

I didn't touch the is_interleaved case—it looks like that case makes a lot of potentially faulty assumptions about the vertex data layout, but that's out of scope for this issue.

**Comment by el-dee** [comment]
> Padded columns are now handled correctly, and the model animates properly now, though it would be great if you could test this on a few models to make sure I haven't broken anything.

I tested with several models with animation and skinning, they all behave correctly.

> 
> I didn't touch the is_interleaved case—it looks like that case makes a lot of potentially faulty assumptions about the vertex data layout, but that's out of scope for this issue.

Out of curiosity, I tested the BoxInterleaved sample from Khronos, the vertex color and normals of some faces look weird. I will test a bit more and, if confirmed, open an issue.
